name: genshin-impact-wish

on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *"
jobs:
  genshin-impact-wish:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
    steps:
    - name: Checkout source
      uses: actions/checkout@v3
      with:
        submodules: true
    - name: Setup Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Run genshin_impact_wish.py
      env:
        GIT_NAME: ${{ secrets.GIT_NAME }}
        GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
      run: |
        pip install --use-pep517 -q -r requirements.txt
        python genshin_impact_wish.py
