# This is a basic workflow to help you get started with Actions

name: genshin-impact-activity

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  genshin-impact-activity:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout source
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      uses: actions/checkout@v3
      with:
        submodules: true
    - name: Setup Python 3.9
      uses: actions/setup-python@v3.1.2
      with:
        python-version: 3.9
    - name: Run genshin_impact_activity.py
      env:
        # Git信息
        GIT_NAME: ${{ secrets.GIT_NAME }}
        GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
        # repo信息
        REPO_NAME: thesixonenine.github.io
        REPO: github.com/thesixonenine/thesixonenine.github.io
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        # 邮件信息
        EMAIL_FROM_USERNAME: ${{ secrets.EMAIL_FROM_USERNAME }}
        EMAIL_FROM_PASSWORD: ${{ secrets.EMAIL_FROM_PASSWORD }}
        EMAIL_FROM_SMTP: ${{ secrets.EMAIL_FROM_SMTP }}
        EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
        EMAIL_TO: ${{ secrets.EMAIL_TO }}
      run: |
        pip3 install -r requirements.txt
        python3 genshin_impact_activity.py
        python3 readme_generator.py
