# This is a basic workflow to help you get started with Actions

name: readme-generate

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    - cron: "0 0,6,8,10,12,14,16,18,20,22 * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  readme-generate:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
    timeout-minutes: 2
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout source
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      uses: actions/checkout@v3
      with:
        submodules: true
    - name: Setup Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Run readme_generator.py
      env:
        # Git信息
        GIT_NAME: ${{ secrets.GIT_NAME }}
        GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
        # repo信息
        REPO_NAME: thesixonenine.github.io
        REPO: github.com/thesixonenine/thesixonenine.github.io
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        pip install --use-pep517 -q -r requirements.txt
        python readme_generator.py
