name: ruankao-notify
on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  ruankao-notify:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
    timeout-minutes: 2
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout source
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GH_TOKEN }}
        submodules: true
    - name: Setup Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Run curl
      env:
        # Git信息
        GIT_NAME: ${{ secrets.GIT_NAME }}
        GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
        # 邮件信息
        EMAIL_FROM_USERNAME: ${{ secrets.EMAIL_FROM_USERNAME }}
        EMAIL_FROM_PASSWORD: ${{ secrets.EMAIL_FROM_PASSWORD }}
        EMAIL_FROM_SMTP: ${{ secrets.EMAIL_FROM_SMTP }}
        EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
        EMAIL_TO: ${{ secrets.EMAIL_TO }}
        KAO_YEAR: "2022年上半年"
      run: |
        curl -s -H "Referer:https://www.ruankao.org.cn/" https://query.ruankao.org.cn/score/main | grep -q "${KAO_YEAR}" && sed -i '4s/^/#/' ./.github/workflows/ruankao-notify.yml && sed -i '5s/^/#/' ./.github/workflows/ruankao-notify.yml && python send_mail.py ruankao "${KAO_YEAR}可查询"
        git add ./.github/workflows/ruankao-notify.yml
        git config --global user.name $GIT_NAME
        git config --global user.email $GIT_EMAIL
        git commit -m "${KAO_YEAR}可查询"
        git push

