name: wechat-pay-notify
on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  wechat-pay-notify:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
    timeout-minutes: 2
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout source
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GH_TOKEN }}
        submodules: true
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Run Bash
      env:
        # Git信息
        GIT_NAME: ${{ secrets.GIT_NAME }}
        GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
        # 邮件信息
        EMAIL_FROM_USERNAME: ${{ secrets.EMAIL_FROM_USERNAME }}
        EMAIL_FROM_PASSWORD: ${{ secrets.EMAIL_FROM_PASSWORD }}
        EMAIL_FROM_SMTP: ${{ secrets.EMAIL_FROM_SMTP }}
        EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
        EMAIL_TO: ${{ secrets.EMAIL_TO }}
      run: |
        ./wechat-pay-notify.sh
